<?php

namespace Drupal\statistics;

use Drupal\Core\Database\Connection;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\State\StateInterface;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Provides the default database storage backend for statistics.
 */
class NodeStatisticsDatabaseStorage extends StatisticsDatabaseStorage  {

  public function recordView($entity_type_id, $key, $id) {
    return parent::recordView($entity_type_id, $key, $id); // TODO: Change the autogenerated stub
  }

  public function fetchView(EntityTypeInterface $entity_type, $id) {
    return parent::fetchView($entity_type, $id); // TODO: Change the autogenerated stub
  }

  public function fetchAll(EntityTypeInterface $entity_type, $order = 'totalcount', $limit = 5) {
    return parent::fetchAll($entity_type, $order, $limit); // TODO: Change the autogenerated stub
  }

  public function deleteViews(EntityTypeInterface $entity_type, $id) {
    return parent::deleteViews($entity_type, $id); // TODO: Change the autogenerated stub
  }

  public function maxTotalCount(EntityTypeInterface $entity_type) {
    return parent::maxTotalCount($entity_type); // TODO: Change the autogenerated stub
  }

  public function createTable(EntityTypeInterface $entity_type) {
    parent::createTable($entity_type); // TODO: Change the autogenerated stub
  }

  public function dropTable(EntityTypeInterface $entity_type) {
    parent::dropTable($entity_type); // TODO: Change the autogenerated stub
  }


}
